config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users

  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  post 'payments/create'
  get 'payments/create'
  get 'payments/purchase'
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#landing_page'
  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Retro bikes Berlin</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons for contact info-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Sofia" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
      <a class="navbar-brand" href="/">Retro Bikes <i class="fas fa-bicycle"></i></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active nav-link"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
          <li class="nav-item nav-link"><%= link_to "About us", simple_pages_about_path %></li>
          <li class="nav-item nav-link"><%= link_to "Contact", simple_pages_contact_path %></li>
          <li class="nav-item nav-link dropdown dropdown-toggle"><%= link_to "Products", products_path, { :id=>"navbarDropdownMenuLink", :role=>"button", "data-toggle"=>"dropdown", "aria-haspopup"=>"true", "aria-expanded"=>"false"} %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "All bikes", products_path, { :class=>"dropdown-item"} %>
            <%= link_to "For Ladies", products_path, { :class=>"dropdown-item"} %>
            <%= link_to "For Gents", products_path, { :class=>"dropdown-item"} %>
          </div>
        </li>
        </ul>

    <div class="form-inline">
      <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
      <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control mr-sm-2", placeholder: "Search for...", "aria-label": "Search" %>
      <%= form.submit 'Search', class: "btn btn-sm btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </div>
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        </li>
        <% end %>
        </li>
        <strong><li class="nav-item nav-link"><%= link_to "My orders", orders_path %></li></strong>
      </ul>
    </div>
  </nav>

  <% if notice %>
      <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p id="alert" class="alert alert-success" role="alert"><%= alert %></p>
  <% end %>

    <%= yield %>



    <%= render 'simple_pages/footer' %>

  </body>
</html>